# Generated by Django 3.1.4 on 2020-12-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_PropsAMC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFilesDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('file_name', models.FileField(upload_to='')),
                ('date_of_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFiles',
        ),
    ]
